import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import ToasterProvider from "@/providers/toaster-provider";
import ClientOnly from "@/components/global/client-only";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          {children}
        </ClientOnly>
      </body>
    </html>
  );
}
